roles:
  communications:
    name: "Communications Agent"
    description: "Convert ideas/feedback into task cards and update roadmap"
    # Cross-model fallback chain: try in order until one succeeds
    model_chain:
      - gemini-2.5-pro                  # Google AI Studio (free-tier keys)
      - deepseek/deepseek-r1-0528:free  # OpenRouter free
      - z-ai/glm-4.5-air:free           # OpenRouter free
    # Legacy fields remain for compatibility when model_chain is absent
    model: "deepseek/deepseek-r1-0528:free"
    providers: ["openrouter"]
    budgets:
      monthly_limit: 50.0
      current_usage: 0.0

  project_manager:
    name: "Project Manager"
    description: "Scope tasks, set acceptance criteria, move to sprint"
    # Cross-model fallback chain: try in order until one succeeds
    model_chain:
      - gemini-2.5-pro                  # Google AI Studio (free-tier keys)
      - deepseek/deepseek-r1-0528:free  # OpenRouter free
      - z-ai/glm-4.5-air:free           # OpenRouter free
    # Legacy fields remain for compatibility when model_chain is absent
    model: "deepseek/deepseek-r1-0528:free"
    providers: ["openrouter"]
    budgets:
      monthly_limit: 100.0
      current_usage: 0.0
    
  senior_dev:
    name: "Senior Developer"
    description: "Handle complex tasks and create subtasks for juniors"
    model_chain:
      - gemini-2.5-pro                  # Google AI Studio (free-tier keys)
      - deepseek/deepseek-r1-0528:free  # OpenRouter free
      - z-ai/glm-4.5-air:free           # OpenRouter free
    model: "deepseek/deepseek-r1-0528:free" 
    providers: ["openrouter"]
    budgets:
      monthly_limit: 200.0
      current_usage: 0.0
    
  junior_dev:
    name: "Junior Developer"
    description: "Implement functions and unit tests"
    model_chain:
      - gemini-2.5-pro                  # Google AI Studio (free-tier keys)
      - deepseek/deepseek-r1-0528:free  # OpenRouter free
      - z-ai/glm-4.5-air:free           # OpenRouter free
    model: "deepseek/deepseek-r1-0528:free"
    providers: ["openrouter"]
    budgets:
      monthly_limit: 50.0
      current_usage: 0.0
    
  release_qa:
    name: "Release QA"
    description: "Create release tests and notes, post release summary"
    model_chain:
      - gemini-2.5-pro                  # Google AI Studio (free-tier keys)
      - deepseek/deepseek-r1-0528:free  # OpenRouter free
      - z-ai/glm-4.5-air:free           # OpenRouter free
    model: "deepseek/deepseek-r1-0528:free"
    providers: ["openrouter"]
    budgets:
      monthly_limit: 75.0
      current_usage: 0.0
